image: ubuntu

environment:
  TWINE_PASS:
    secure: l5f9zb54AYJ/kZgpYI2NGtktBACOM6jA1oQkrzz6wuI=

build_script:
  - sudo pip install wheel
  - sh: |
      [[ "$APPVEYOR_REPO_TAG" = "true" ]] && export VERSION=$APPVEYOR_REPO_TAG_NAME || echo "No tag found"
  - python setup.py bdist_wheel
  - sh: |
      [[ "$APPVEYOR_REPO_TAG" = "false" ]] && rm -rf wheelhouse/* || echo "Tagged build, not deleting artifacts"
artifacts:
  - path: "dist\\*.whl"
    name: Outputs

deploy_script:
    - sh: sudo pip install -U twine
    - sh: |
        [[ "$APPVEYOR_REPO_TAG" = "true" && "$APPVEYOR_REPO_BRANCH" = "master" && -z "$APPVEYOR_PULL_REQUEST_NUMBER" ]] && twine upload -u safijari -p $TWINE_PASS dist/* || echo "Nothing to deploy"
